nelmio_api_doc:
    documentation:
        info:
            title: Anisco API 
            description: Documentation API de mon projet.
            version: 1.0.0
        servers:
            - url: http://localhost:8000
              description: Serveur local
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
    areas:
        path_patterns:
            - ^/api(?!/doc$) # Documenter seulement les routes sous /api
