nelmio_api_doc:
    documentation:
        info:
            title: API Documentation
            description: Documentation des API pour le projet Modelis_tech
            version: 1.0.0
            resource: '@NelmioApiDocBundle/Resources/config/routing/swaggerui.xml'
            type: rest
            prefix: /api/doc
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
